site_name: 刹那的博客

edit_uri: blob/main/docs

theme:
  name: material
  language: zh

  # 设置网页的字体，来源于Google Font
  font:
    # 文本的字体
    text: Noto Sans Simplified Chinese
    # 代码的字体
    code: Noto Sans Mono

  icon:
    repo: fontawesome/brands/git-alt
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate   # integration for the table of content
    - navigation.top  # back to top button
    - search.suggest
  
  plugins:
  - search:
      lang: zh

repo_name: Setsuna-F-0422/My-Site
repo_url: https://github.com/Setsuna-F-0422/My-Site

# markdown插件，丰富浏览体验
markdown_extensions:
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

copyright: Copyright &copy; Cary Xu all right reserved

extra_css:
  - stylesheets/extra.css
