site_name: 刹那的博客
edit_uri: blob/main/docs
repo_name: Setsuna-F-0422/My-Site
repo_url: https://github.com/Setsuna-F-0422/My-Site
copyright: Copyright &copy; Cary Xu all right reserved

nav:
  - 主页: index.md
  - 转载:
    - ./reprint/index.md
    - 一位革命老人对未来革命的几点思考: ./reprint/Weiwei-on-Future-Revolution.md

theme:
  name: material
  language: zh

  # 设置网页的字体，来源于Google Font
  font:
    # 文本的字体
    text: Noto Sans Simplified Chinese
    # 代码的字体
    code: Roboto

  icon:
    repo: fontawesome/brands/git-alt
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # 主色调
      primary: indigo
      # 点击时显示的颜色
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - toc.integrate   # integration for the table of content
    - navigation.top  # back to top button
    - search.suggest
  
  plugins:
  - search:
      lang: zh

# markdown插件，丰富浏览体验
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
